// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ResRegister.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ResRegister_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ResRegister_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3018000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3018000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ResRegister_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ResRegister_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ResRegister_2eproto;
namespace protoAuth {
class RegisterationRespose;
struct RegisterationResposeDefaultTypeInternal;
extern RegisterationResposeDefaultTypeInternal _RegisterationRespose_default_instance_;
}  // namespace protoAuth
PROTOBUF_NAMESPACE_OPEN
template<> ::protoAuth::RegisterationRespose* Arena::CreateMaybeMessage<::protoAuth::RegisterationRespose>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace protoAuth {

enum RegisterationRespose_eRegResult : int {
  RegisterationRespose_eRegResult_SUCCESS = 0,
  RegisterationRespose_eRegResult_ACCOUNT_ALREADY_EXISTS = 1,
  RegisterationRespose_eRegResult_PASSWORD_CONDITION_CHECK = 2,
  RegisterationRespose_eRegResult_INTERNAL_SERVER_ERROR = 3
};
bool RegisterationRespose_eRegResult_IsValid(int value);
constexpr RegisterationRespose_eRegResult RegisterationRespose_eRegResult_eRegResult_MIN = RegisterationRespose_eRegResult_SUCCESS;
constexpr RegisterationRespose_eRegResult RegisterationRespose_eRegResult_eRegResult_MAX = RegisterationRespose_eRegResult_INTERNAL_SERVER_ERROR;
constexpr int RegisterationRespose_eRegResult_eRegResult_ARRAYSIZE = RegisterationRespose_eRegResult_eRegResult_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* RegisterationRespose_eRegResult_descriptor();
template<typename T>
inline const std::string& RegisterationRespose_eRegResult_Name(T enum_t_value) {
  static_assert(::std::is_same<T, RegisterationRespose_eRegResult>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function RegisterationRespose_eRegResult_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    RegisterationRespose_eRegResult_descriptor(), enum_t_value);
}
inline bool RegisterationRespose_eRegResult_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, RegisterationRespose_eRegResult* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<RegisterationRespose_eRegResult>(
    RegisterationRespose_eRegResult_descriptor(), name, value);
}
// ===================================================================

class RegisterationRespose final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protoAuth.RegisterationRespose) */ {
 public:
  inline RegisterationRespose() : RegisterationRespose(nullptr) {}
  ~RegisterationRespose() override;
  explicit constexpr RegisterationRespose(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RegisterationRespose(const RegisterationRespose& from);
  RegisterationRespose(RegisterationRespose&& from) noexcept
    : RegisterationRespose() {
    *this = ::std::move(from);
  }

  inline RegisterationRespose& operator=(const RegisterationRespose& from) {
    CopyFrom(from);
    return *this;
  }
  inline RegisterationRespose& operator=(RegisterationRespose&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RegisterationRespose& default_instance() {
    return *internal_default_instance();
  }
  static inline const RegisterationRespose* internal_default_instance() {
    return reinterpret_cast<const RegisterationRespose*>(
               &_RegisterationRespose_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(RegisterationRespose& a, RegisterationRespose& b) {
    a.Swap(&b);
  }
  inline void Swap(RegisterationRespose* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RegisterationRespose* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline RegisterationRespose* New() const final {
    return new RegisterationRespose();
  }

  RegisterationRespose* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<RegisterationRespose>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RegisterationRespose& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const RegisterationRespose& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RegisterationRespose* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protoAuth.RegisterationRespose";
  }
  protected:
  explicit RegisterationRespose(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef RegisterationRespose_eRegResult eRegResult;
  static constexpr eRegResult SUCCESS =
    RegisterationRespose_eRegResult_SUCCESS;
  static constexpr eRegResult ACCOUNT_ALREADY_EXISTS =
    RegisterationRespose_eRegResult_ACCOUNT_ALREADY_EXISTS;
  static constexpr eRegResult PASSWORD_CONDITION_CHECK =
    RegisterationRespose_eRegResult_PASSWORD_CONDITION_CHECK;
  static constexpr eRegResult INTERNAL_SERVER_ERROR =
    RegisterationRespose_eRegResult_INTERNAL_SERVER_ERROR;
  static inline bool eRegResult_IsValid(int value) {
    return RegisterationRespose_eRegResult_IsValid(value);
  }
  static constexpr eRegResult eRegResult_MIN =
    RegisterationRespose_eRegResult_eRegResult_MIN;
  static constexpr eRegResult eRegResult_MAX =
    RegisterationRespose_eRegResult_eRegResult_MAX;
  static constexpr int eRegResult_ARRAYSIZE =
    RegisterationRespose_eRegResult_eRegResult_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  eRegResult_descriptor() {
    return RegisterationRespose_eRegResult_descriptor();
  }
  template<typename T>
  static inline const std::string& eRegResult_Name(T enum_t_value) {
    static_assert(::std::is_same<T, eRegResult>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function eRegResult_Name.");
    return RegisterationRespose_eRegResult_Name(enum_t_value);
  }
  static inline bool eRegResult_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      eRegResult* value) {
    return RegisterationRespose_eRegResult_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kReqIdFieldNumber = 1,
    kResultFieldNumber = 2,
  };
  // required int32 reqId = 1;
  bool has_reqid() const;
  private:
  bool _internal_has_reqid() const;
  public:
  void clear_reqid();
  ::PROTOBUF_NAMESPACE_ID::int32 reqid() const;
  void set_reqid(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_reqid() const;
  void _internal_set_reqid(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // required .protoAuth.RegisterationRespose.eRegResult result = 2;
  bool has_result() const;
  private:
  bool _internal_has_result() const;
  public:
  void clear_result();
  ::protoAuth::RegisterationRespose_eRegResult result() const;
  void set_result(::protoAuth::RegisterationRespose_eRegResult value);
  private:
  ::protoAuth::RegisterationRespose_eRegResult _internal_result() const;
  void _internal_set_result(::protoAuth::RegisterationRespose_eRegResult value);
  public:

  // @@protoc_insertion_point(class_scope:protoAuth.RegisterationRespose)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::int32 reqid_;
  int result_;
  friend struct ::TableStruct_ResRegister_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RegisterationRespose

// required int32 reqId = 1;
inline bool RegisterationRespose::_internal_has_reqid() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool RegisterationRespose::has_reqid() const {
  return _internal_has_reqid();
}
inline void RegisterationRespose::clear_reqid() {
  reqid_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 RegisterationRespose::_internal_reqid() const {
  return reqid_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 RegisterationRespose::reqid() const {
  // @@protoc_insertion_point(field_get:protoAuth.RegisterationRespose.reqId)
  return _internal_reqid();
}
inline void RegisterationRespose::_internal_set_reqid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000001u;
  reqid_ = value;
}
inline void RegisterationRespose::set_reqid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_reqid(value);
  // @@protoc_insertion_point(field_set:protoAuth.RegisterationRespose.reqId)
}

// required .protoAuth.RegisterationRespose.eRegResult result = 2;
inline bool RegisterationRespose::_internal_has_result() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool RegisterationRespose::has_result() const {
  return _internal_has_result();
}
inline void RegisterationRespose::clear_result() {
  result_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::protoAuth::RegisterationRespose_eRegResult RegisterationRespose::_internal_result() const {
  return static_cast< ::protoAuth::RegisterationRespose_eRegResult >(result_);
}
inline ::protoAuth::RegisterationRespose_eRegResult RegisterationRespose::result() const {
  // @@protoc_insertion_point(field_get:protoAuth.RegisterationRespose.result)
  return _internal_result();
}
inline void RegisterationRespose::_internal_set_result(::protoAuth::RegisterationRespose_eRegResult value) {
  assert(::protoAuth::RegisterationRespose_eRegResult_IsValid(value));
  _has_bits_[0] |= 0x00000002u;
  result_ = value;
}
inline void RegisterationRespose::set_result(::protoAuth::RegisterationRespose_eRegResult value) {
  _internal_set_result(value);
  // @@protoc_insertion_point(field_set:protoAuth.RegisterationRespose.result)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protoAuth

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::protoAuth::RegisterationRespose_eRegResult> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::protoAuth::RegisterationRespose_eRegResult>() {
  return ::protoAuth::RegisterationRespose_eRegResult_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ResRegister_2eproto
